# This is the final, definitive workflow using a "Run From Package" strategy.

name: Build and deploy Python project to Azure Function App - sallee-agent-tools

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-functions/python:4-python3.11
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ========================================================================
      # == THE FINAL, CRITICAL FIX: Install dependencies INTO the package     ==
      # == This creates a self-contained application for deployment.          ==
      # ========================================================================
      - name: Install dependencies into a deployable package
        run: pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_330CD28847404624A93A5896BC161F0D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1575CBF5C29E40FCAF3F4EF02943FF3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91667B75A9C84E688B2F047EB125EDCA }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'sallee-agent-tools'
          package: 'release.zip'
